### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Tealium/tealium-cookie-match-gtm-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on vdataEndpoint and params when generating the url
pixel = config.url + vdataEndpoint + params.join('&');

**Comment by tygavin** [comment]
@praveena-pappu Thank you for reviewing.  I agree with you. Most of the vendors support this (as you can see in other parts of the template).

The "xandr" documentation however does not describe their URL format this way:

https://wiki.xandr.com/display/supply/User+ID+Mapping

Their endpoint and their documentation shows the following string:

`https://secure.adnxs.com/getuid?http://ad.adserver.com/pixel?user_id=$UID`
